# Generated by Django 5.2 on 2025-05-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_room_room_image_alter_room_room_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_nimber',
            new_name='room_number',
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(default='No description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='room_image',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/'),
        ),
    ]
