# Generated by Django 5.2 on 2025-05-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_room_nimber_room_room_number_room_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_image',
            field=models.ImageField(default='jamin', upload_to='room_images/'),
            preserve_default=False,
        ),
    ]
