# Generated by Django 5.2 on 2025-05-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_room_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_email',
            field=models.EmailField(default='customer_email', max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_name',
            field=models.CharField(default='customer_name', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_phone',
            field=models.CharField(default='customer_phone', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='room_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Suite', 'Suite'), ('Deluxe', 'Deluxe'), ('Family', 'Family'), ('Presidential', 'Presidential')], default='single', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=8),
        ),
    ]
