# Generated by Django 5.2 on 2025-05-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_booking_customer_email_booking_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_phone',
            field=models.CharField(default='customer_phone', max_length=10),
        ),
    ]
