# Generated by Django 5.2 on 2025-05-06 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_user_customer_name_alter_booking_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='about_images/')),
                ('title', models.CharField(default='About Us', max_length=100)),
                ('description', models.TextField(default='Description about the hotel.')),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer_phone',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
